config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get "/dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists, only: [:index, :show] do
    resources :tattoos, only: [:index]
    resources :appointments
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :artist
  has_attachment :photo
  # has_one :review
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :studio
  has_many :tattoos
  has_many :appointments
  has_many :reviews
  geocoded_by :location
  after_validation :geocode, if: :location_changed?
end

app/models/review.rb
class Review < ApplicationRecord
  # belongs_to :appointment
  # has_one :artist, through: :appointment
  belongs_to :artist

  after_save :update_artist_rating, if: :rating_changed?

  def update_artist_rating
    # self.artist.rating = 0 if self.artist.rating.nil?
    all_ratings = self.artist.reviews.reduce(0) { |a, r| a + r.rating }
    self.artist.rating = all_ratings / self.artist.reviews.length.to_f
    self.artist.save
  end
end

app/models/studio.rb
class Studio < ApplicationRecord
  geocoded_by :location
  after_validation :geocode, if: :location_changed?
end

app/models/tattoo.rb
class Tattoo < ApplicationRecord
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_many :appointments

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:email] = auth.fetch(:email,"#{user_params[:uid]}@#{user_params[:provider]}.com")
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h
    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.

    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.appointment_date = appointment_params[:appointment_date].to_date
    @artist = Artist.find(params[:artist_id])
    @appointment.artist = @artist
    @appointment.user = current_user
    if @appointment.save
      redirect_to dashboard_path
    else
      render "artists/show"
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
  end



  private

  def appointment_params
    params.require(:appointment).permit(:status, :appointment_date, :appointment_time, :photo)
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  include ArtistHelper
  skip_before_action :authenticate_user!

  def index
    @artists = Artist.all
    @locations = Artist.all.map { |a| a.location }.uniq
    # @studio = Studio.where.not(latitude: nil, longitude: nil)
    @artist2 = Artist.where.not(latitude: nil, longitude: nil)
    @artist_excluded = @artist2.select { |artist| artist.location.split(" ")[-1] == params[:location] }
        # if artist.location.split(" ")[-1] == params[:location]
        @hash = Gmaps4rails.build_markers(@artist_excluded) do |flat, marker|
          marker.lat flat.latitude
          marker.lng flat.longitude
        end


    @l_array = ["Barcelona", "Paris", "London", "Berlin", "Madrid", "Rome", "Geneva"]


  end


  def show
    @artist = Artist.find(params[:id])
    @appointment = Appointment.new
    @time_slots = generate_slots(10, 18)
    @artist2_coordinates = { lat: @artist.latitude, lng: @artist.longitude}
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @locations = Artist.all.map { |a| a.location }.uniq
  end

  def dashboard
    @locations = Artist.all.map { |a| a.location }.uniq
    @appointments = current_user.appointments
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @reviews = Review.all
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # @review.appointment = Appointment.find(params[:appointment_id])
    @artist = Artist.find(params[:artist_id])
    @review.artist = @artist
    if @review.save
      redirect_to @review.artist
    else
      render :new
    end
  end

  private

  def avg_rating
    @artist = Artist.find(params[:artist_id])
    ratings = []
    @artist.reviews.each do |review|
      ratings << review.rating
    end

    @avg_rating = (ratings.inject(:+)/ratings.count).to_i
    @artist.rating = @avg_rating
    @artist.save
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/controllers/tattoos_controller.rb
class TattoosController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @tattoos = Tattoo.all
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])
    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
  def generate_slots(start, finish)
    start.upto(finish).map { |t| ["#{t}:00", "#{t}:00"] }
  end
end

app/views/artists/index.html.erb
<script src="https://code.jquery.com/jquery-3.2.1.js"> </script>


<div class="container background-white">
  <div class="row">
    <div class="col s6 offset-s4  background-white  margin-top-100px">
      <%= form_tag "/artists", method: "get", class: 'fixed search-form z-depth-1' do %>
      <%= select_tag 'location', options_for_select(@l_array), class: 'search-form-select' %>

      <%= submit_tag "Discover Art", class: 'btn-search' %>
      <% end %>
    </div>
  </div>
</div>

<div class="wrapper-artists-index">
  <!-- Parent container-fluid to avoid large paddings on sides -->
  <div class="container-fluid">

    <!-- search bar on this page also -->


    <div class="row">
      <!-- Left side of screen, cards go here in a nested grid -->
      <div class="col-xs-12 col-md-7">
        <div class="row">
          <% @artists.each do |artist| %>
          <% if artist.location.split(" ")[-1] == params[:location] %>
          <!-- col for each card -->
          <div class="col-xs-12">
            <!-- Card -->
            <div class="card-artists-index">
              <div class="row">
                <div class="col-xs-12 col-md-4" style="margin-top: 30px">
                <%= image_tag "http://assets.rebelcircus.com/blog/wp-content/uploads/2015/05/evancheesepicweb.jpg", class: "image-rect" %>
                  <br>
                  <%= link_to artist.name, artist_path(artist.id), class: "link-black" %>

                  <ul class="list-inline">
                    <% if artist.rating  %>
                    <% artist.rating.times do  %>
                    <li><i class="fa fa-star" aria-hidden="true" style="color: black"></i></li>
                    <% end %>
                    <% (5 - artist.rating).times do %>
                    <li><i class="fa fa-star-o" aria-hidden="true" style="color: black"></i></li>
                    <% end %>
                    <% end %>
                  </ul>
                </div>
                <div class="col-xs-12 col-md-8">
                  <div class="row" >
                    <div class="col-xs-12 col-margin-top col-1">
                      <p>Recent work</p>
                    </div>
                    <div class="col-xs-12 col-2">
                      <%= image_tag "https://s-media-cache-ak0.pinimg.com/originals/9d/47/c1/9d47c11896fba664763cfb4e58553a89.jpg", class: "image-squre" %>
                      <%= image_tag "https://s-media-cache-ak0.pinimg.com/736x/20/f5/37/20f537bd1c921b36520f241afb5d7a21.jpg", class: "image-squre" %>
                      <%= image_tag "https://s-media-cache-ak0.pinimg.com/736x/86/4a/b1/864ab15ca8fce9158f77083d16ae6908.jpg", class: "image-squre" %>
                      <%= image_tag "https://s-media-cache-ak0.pinimg.com/736x/8a/12/17/8a12176e22559abb4a58c087f2dc265f.jpg", class: "image-squre" %>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
      <!-- Right side of screen, map goes here -->
      <div class="col-xs-12 col-md-5">

        <!-- Div to draw a map in -->







        <div id="map"></div>



      </div>
    </div>
  </div>
</div>


<!-- Content_for, leave it at the bottom, don't insert into layout. Or I will throw poop at you. -->

<% content_for(:after_js) do %>
<script>
  $(document).ready(function() {
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  });
</script>


<% end %>

app/views/artists/show.html.erb
<!-- <div class="wrapper-artists-show" >
  <div class="container-fluid"> -->

    <div class="container-position-relative">
      <div class="row margin-top-100px">
        <div class="header col-xs-offset-2 col-xs-3">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsoF-V9AXxHDCer4JTrmV7ssfjOZSnFRMEhBlZGFtxYCzGlJd7GA" class="avatar-xl avatar-artist-show">
        </div>
        <div class="artist-pages-info col-xs-6">
          <h2><%=@artist.name%></h2>
          <h5><%= @artist.location %></h5>

          <ul class="list-inline">
            <% if @artist.rating  %>
            <% @artist.rating.times do  %>
            <li><i class="fa fa-star" aria-hidden="true" style="color: black"></i></li>
            <% end %>
            <% (5 - @artist.rating).times do %>
            <li><i class="fa fa-star-o" aria-hidden="true" style="color: black"></i></li>
            <% end %>
            <% end %>
          </ul>


          <h4>About <%= @artist.name %></h4>

          <p><%= @artist.info %></p>
          <a href="#modal1" class="btn btn-search">Book an appointment</a>

        </div>
      </div>
    </div>
 <!--  </div>

</div> -->

<% image = Faker::Placeholdit.image("50x50", 'jpg')  %>
<div class="container-position-relative text-center">
  <div class ="row">
    <img src="https://s-media-cache-ak0.pinimg.com/736x/0a/68/91/0a68918afbff7a5ececc4e428bd765f1.jpg" width="200px" height="200px">
    <img src="https://s-media-cache-ak0.pinimg.com/736x/58/dc/3e/58dc3e227487845e385b6994872843cb.jpg" width="200px" height="200px">
    <img src="https://s-media-cache-ak0.pinimg.com/originals/9d/47/c1/9d47c11896fba664763cfb4e58553a89.jpg" width="200px" height="200px">
  </div>
  <div class="row">
    <img src="https://static1.squarespace.com/static/56a3c2a4c647ade23fdcce47/56c33d407da24f852dcc0942/56c33e62d51cd4074a311bba/1455636086809/IMG_3607.JPG" width="200px" height="200px">
    <img src="https://s-media-cache-ak0.pinimg.com/736x/cd/e8/e5/cde8e51614bffa8f21cca3c5082a0650.jpg" width="200px" height="200px">
    <img src="http://static.boredpanda.com/blog/wp-content/uploads/2016/12/gustav-klimt-tattoo-3-5845196236dba__700.jpg" width="200px" height="200px">
  </div>
  <div class="row">
    <img src="https://s-media-cache-ak0.pinimg.com/736x/b9/01/ea/b901eaf0940c269b4bee7b5256f46e2f.jpg" width="200px" height="200px">
    <img src="https://s-media-cache-ak0.pinimg.com/736x/34/65/54/346554ff16ef029254c3472ede7e7799.jpg" width="200px" height="200px">
    <img src="https://s-media-cache-ak0.pinimg.com/originals/8f/8f/7e/8f8f7ed11e440d14cae6d8a5b4ef2bc7.jpg" width="200px" height="200px">
  </div>
</div>

</div>

</div>

</div>
</div>


<div id="modal1" class="modal">
  <div class="modal-content">
    <%= simple_form_for [@artist, @appointment] do |f| %>
    <%= f.input :appointment_date, as: :string, input_html: { class: 'datepicker' } %>

    <%= f.collection_radio_buttons :appointment_time, @time_slots, :first, :last, item_wrapper_class: 'with-gap' %>


    <%= f.input :photo, as: :attachinary %>

    <br><br>
    <%= f.button :submit, class: "btn-search btn-primary" %>
    <% end %>
  </div>
</div>






<div class="text-center">
  <h3>Reviews of <%=@artist.name  %></h3>
  <%= link_to "Leave a Review", new_artist_review_path(@artist) %>
  <div>
    <% @artist.reviews.each do |review| %>
    <%= review.content %>
    <ul class="list-inline">
      <% review.rating.times do %>
      <li><i class="fa fa-star" aria-hidden="true" style="color: black"></i></li>
      <% end %>
      <% (5 - review.rating).times do %>
      <li><i class="fa fa-star-o" aria-hidden="true" style="color: black"></i></li>
      <% end %>
      <br>
      <br>
    </ul>
    <% end %>
  </div>
</div>



<% content_for(:after_js) do %>
<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').pickadate({
      weekStart: 1,
      todayBtn: true,
      min: Date.now(),
      todayHighlight: true,
      format: "dd/mm/yyyy"
    });
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Inkd</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
  <% if params[:controller] == 'pages' && params[:action] == 'home'%>
  <%= render 'shared/navbar-landing' %>
  <% else %>
  <%= render 'shared/navbar' %>
  <% end %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
  <%= yield(:after_js) %>
</body>
</html>

app/views/pages/about.html.erb
<img class="idiots" src="" />

app/views/pages/dashboard.html.erb
<div class="beyond-header">
</div>

<% @appointments.each do |appointment| %>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2 text-center">
    <h4>Your Next Appointment </h4>
  </div>
  </div>

  <div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="artist-info">
      <div class="artist-details">
        <div class="artist">
          <img src="http://www.unsplash.it/200/200" class="avatar-xl" alt="">
          <%= appointment.artist.name %>
        </div>
        <div class="details text-center">
        <ul class="list-unstyle">
       <li> <%= appointment.artist.location %> </li>
        <li>  <%= link_to("http://maps.google.com/maps?q=#{appointment.artist.latitude},#{appointment.artist.longitude}") do %>
        <i class="fa fa-map-marker" aria-hidden="true"> </i>  See Location
       <% end %> </li>
        <li> <%= link_to appointment.artist do %>
        <i class="fa fa-user" aria-hidden="true"></i> <p>  Tatmaster profile </p> </li>
        <% end %>
         <li> <%= link_to ("https://www.instagram.com/explore/tags/#{appointment.artist.name}") do %>
        <i class="fa fa-instagram" aria-hidden="true"></i> <p>  Work on Instagram </p> </li>
        <% end %>
        </ul>
        </div>
      </div>
      <div class="appointment-status">
      <ul class="list-unstyle text-center">
         <li> Awaiting Confirmation </li>
         <br>
         <li> Hourly rate <br>  $<%= appointment.artist.rate %>.00 </li>

        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
   <!--  <div class="order-description"> <h4>Order description: </h4> <br>
    This is a really cool tattoo that will change my life. I hope to get
    a lot of attention, the attention I've always been
    neglected
    </div> -->
    <div class="sketches">
    <h4> Your Sketches </h4>
    <div class="sketches-collection text-center">
    <%= link_to appointment.photo.path do %>
      <%= cl_image_tag appointment.photo.path, width: 200, height: 150, crop: :fill  %>
      <% end %>
    </div>
    <br>
    <div class="sketches-button">
      <%= simple_form_for [appointment.artist, appointment] do |f| %>
       <%= f.input :photo, as: :attachinary, label: "Upload Sketch" %>
       <% end %>
      <%= link_to "Contact Artist", ("mailto:#{appointment.artist.name}@tatmaster.com"), class: "waves-effect waves-teal btn" %>
    </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="edit-cancel">
        <%= link_to "Cancel Appointment", artist_appointment_path(appointment.artist, appointment), method: :delete  %>
<!--           <a class="btn-flat">Edit</a>
 -->          <!-- <a class="btn-flat">Delete</a> -->
      </div>
    </div>
  </div>
</div>



    <% end %>

  </div>
</div>

</div>

app/views/pages/home.html.erb
<%     @l_array = ["Barcelona", "Paris", "London", "Berlin", "Madrid", "Rome", "Geneva"]
 %>



<div class="banner-landing-page">
  <h1>Get Inked by top local artists</h1>
  <h2>Discover new works and book an appointment</h2>
  <div>

    <%= form_tag "/artists", method: "get", class: 'form-banner' do %>
    <%= select_tag 'location', options_for_select(@l_array), class: 'select-pages-home' %>
    <%= submit_tag "Discover Art", class: 'btn-landing' %>
    <% end %>


  </div>
</div>

<div class="container">
  <div class="row margin-top-20">
    <div class="col s12 l6">
      <h2>What’s Inkd?</h2>
      <h3>Location</h3>
      <p>Travelling to a new city and want to keep
       memory? It's easy with unique tattoo from
       local artists you cand find anywhere.</p>
       <h3>Artists</h3>
       <p>Top artists willing to provide you the best services
        at reasonable prices. Explore galleries of works
        and filter by location, style, or rating.</p>
        <h3>Feedback</h3>
        <p>Like your new artist? Give your arist a review and
          follow their profile.</p>
        </div>
        <div class="col s12 l6 margin-top-20">
          <img src="http://i.imgur.com/Ed5RNp7.png" class="img-responsive z-depth-3">
        </div>
      </div>
    </div>
    <h3 class="text-center">Featured Artists</h3>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <div class="top-artist-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa6UsbobagjLguJnwr_axgiwVIWYZEkG06X0gWfpLZZXJRDtTY');">
            <div class="top-artist-name">SAM JIMINEZ</div>
            <div class="top-artist-city">
              <p>Geneva</p>
            </div>
            <a class="card-link" href="#" ></a>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="top-artist-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3Ce-u-QplJYxIdEu_zwBmokw3Amc8tYsMPvQvsJ0EBZN6aL6_Yg');">
            <div class="top-artist-name">CARMEN SANDIEGO </div>
            <div class="top-artist-city">
              <p>Paris</p>
            </div>
            <a class="card-link" href="#" ></a>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="top-artist-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFPMTO7c2p7J2Qox9E-Bd_1VR7TfW2mw_xeMHQlwn3NT4jBqZ3eQ');">
            <div class="top-artist-name">KAYTLYN DEFRANCESCO</div>
            <div class="top-artist-city">
              <p>Barcelona</p>
            </div>
            <a class="card-link" href="#" ></a>
          </div>
        </div>
      </div>
    </div>

app/views/reviews/new.html.erb
<div class="container-review">
<h1>Leave a review</h1>

<%= simple_form_for [@artist, @review] do |f| %>
<%= f.text_field :content %>
<%= f.select :rating , options_for_select(%w(0 1 2 3 4 5)) %>
<%= f.submit %>
<% end %>
</div>

app/views/shared/_navbar-landing.html.erb
<div class="navbar-wagon-pages-home navbar-fixed-top">
  <div class="container">
    <div class="navbar-left">
      <%= link_to "Inkd", root_path, class: "navbar-landing-link-logo"%>
    </div>
    <div class="navbar-right">

      <% if user_signed_in? %>

      <div class="navbar-item">
        <div class="dropdown">
          <%= image_tag "http://bit.ly/2s1EvE7", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <% else %>

      <div class="hidden-xs">
        <%= link_to t(".sign_in", default: "About"), root_path, class: "navbar-item navbar-landing-link" %>
        <span class="navbar-item-vertical-line">|</span>
        <%= link_to t(".sign_in", default: "Sign In"), new_user_session_path, class: "navbar-item navbar-landing-link" %>
        <%= link_to t(".top_call_to_action", default: "Sign Up"), new_user_registration_path , class: "navbar-item navbar-landing-link" %>
      </div>

      <div class="hidden-sm hidden-md hidden-lg">
        <i class="fa fa-bars dropdown-toggle fa-white navbar-item" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>

      <% end %>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon-pages-everywhere navbar-fixed-top">
  <div class="container">
    <div class="navbar-left">
      <%= link_to "Inkd", root_path, class: "navbar-landing-link-logo"%>
    </div>
    <div class="navbar-right">

      <% if user_signed_in? %>

      <div class="navbar-item">
        <div class="dropdown">
          <%= image_tag "http://bit.ly/2s1EvE7", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <% else %>

      <div class="hidden-xs">
        <%= link_to t(".sign_in", default: "About"), root_path, class: "navbar-item navbar-landing-link" %>
        <span class="navbar-item-vertical-line">|</span>
        <%= link_to t(".sign_in", default: "Sign In"), new_user_session_path, class: "navbar-item navbar-landing-link" %>
        <%= link_to t(".top_call_to_action", default: "Sign Up"), new_user_registration_path , class: "navbar-item navbar-landing-link" %>
      </div>

      <div class="hidden-sm hidden-md hidden-lg">
        <i class="fa fa-bars dropdown-toggle fa-white navbar-item" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>

      <% end %>

    </div>
  </div>
</div>